variables:
  MAJOR_VERSION: "2"
  MINOR_VERSION: "1"
  MAINTENANCE_VERSION: "0"
  DOCKER_PUBLISH_ENABLED: 'false'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
