variables:
  APP_NAME: "th2-common"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "6"
  MAINTENANCE_VERSION: "0"
  DOCKER_PUBLISH_ENABLED: 'false'
  ARTIFACTORY_PUBLISH_ENABLED: 'true'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
