name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.sha }}
    - name: Checkout tool
      uses: actions/checkout@v6
      with:
        repository: exactpro-th2/ci-github-action
        ref: master
        token: ${{ secrets.PAT_CI_ACTION }}
        path: ci-github-action
    - name: Run CI action
      uses: ./ci-github-action
      with:
        ref: ${{ github.sha }}
