name: Dev build and publish Java distributions to sonatype snapshot repository

on:
  push:
    branches-ignore:
    - master
    - version-*
    # paths:
    # - gradle.properties
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
# Prepare custom build version
      - name: Get branch name
        id: branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
      - name: Get release_version
        id: ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
      - name: Build custom release version
        id: release_ver
        run: echo ::set-output name=value::"${{ steps.ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}-SNAPSHOT"
      - name: Write custom release version to file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
          value: ${{ steps.release_ver.outputs.value }}
      - name: Show custom release version
        run: echo ${{ steps.release_ver.outputs.value }}
# Build and publish package
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew --info clean build publish
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }} 

